/:
  controller: "User"
  action: "login"

/deconnexion:
  controller: "User"
  action: "deconnecter"

/dashboard: 
  controller: "Dashboard"
  action: "dashboard"

/mailbox:
  controller: "Mail"
  action: "mail"

/apparence:
  controller: "Apparence"
  action: "apparence"

/front:
  controller: "Front"
  action: "frontforum"

/front/ajout-article:
  controller: "Front"
  action: "addarticle"

/front/article:
  controller: "Front"
  action: "updatearticleview"

/front/modificaton-article:
  controller: "Front"
  action: "updatearticle"

/front/resolution-article:
  controller: "Front"
  action: "resolvearticle"

/front/suppression-article:
  controller: "Front"
  action: "removearticle"

/front/lire-article:
  controller: "Front"
  action: "readarticle"

/front/ajout-message:
  controller: "Front"
  action: "addmessage"

/front/message:
  controller: "Front"
  action: "updatemessageview"

/front/modification-message:
  controller: "Front"
  action: "updatemessage"

/front/suppression-message:
  controller: "Front"
  action: "removemessage"

/forum: 
  controller: "Forum"
  action: "forum"

/forum/ajout-article:
  controller: "Forum"
  action: "addarticle"

/forum/article:
  controller: "Forum"
  action: "updatearticleview"

/forum/modificaton-article:
  controller: "Forum"
  action: "updatearticle"

/forum/resolution-article:
  controller: "Forum"
  action: "resolvearticle"

/forum/suppression-article:
  controller: "Forum"
  action: "removearticle"

/forum/lire-article:
  controller: "Forum"
  action: "readarticle"

/forum/ajout-message:
  controller: "Forum"
  action: "addmessagearticle"

/forum/message:
  controller: "Forum"
  action: "updatemessagearticleview"

/forum/modification-message:
  controller: "Forum"
  action: "updatemessagearticle"

/forum/suppression-message:
  controller: "Forum"
  action: "removemessagearticle"

/forum/bannir-utilisateur:
  controller: "Forum"
  action: "banuser"

/forum/ajout-categorie:
  controller: "Forum"
  action: "addcategory"

/forum/categorie:
  controller: "Forum"
  action: "updatecategoryview"

/forum/modification-categorie:
  controller: "Forum"
  action: "updatecategory"

/forum/suppression-categorie:
  controller: "Forum"
  action: "removecategory"

/media: 
  controller: "Media"
  action: "media"

/page: 
  controller: "Page"
  action: "page"

/lien: 
  controller: "Page"
  action: "lien"

/parametre:
  controller: "Parametre"
  action: "parametre"

/gestionuser:
  controller: "User"
  action: "gestionuser"

/ajout-utilisateur:
  controller: "User"
  action: "add"


/recupcode:
  controller: "User"
  action: "recupcode"

/changemdp:
  controller: "User"
  action: "changemdp"

/supprimer-utilisateur:
  controller: "User"
  action: "remove"

/utilisateur:
  controller: "User"
  action: "default"

/inscription:
  controller: "User"
  action: "register"

/mdpoublie:
  controller: "User"
  action: "forget"