/:
  controller: "User"
  action: "login"

/deconnexion:
  controller: "User"
  action: "deconnecter"

/dashboard: 
  controller: "Dashboard"
  action: "dashboard"

/mailbox:
  controller: "Mail"
  action: "mail"

/apparence:
  controller: "Apparence"
  action: "apparence"

/forum: 
  controller: "Forum"
  action: "forum"

/ajout-article:
  controller: "Forum"
  action: "addarticle"

/lire-article:
  controller: "Forum"
  action: "readarticle"

/ajout-message:
  controller: "Forum"
  action: "addmessagearticle"

/article-resolu:
  controller: "Forum"
  action: "resolvearticle"

/media: 
  controller: "Media"
  action: "media"

/page: 
  controller: "Page"
  action: "page"

/lien: 
  controller: "Page"
  action: "lien"

/parametre:
  controller: "Parametre"
  action: "parametre"

/gestionuser:
  controller: "User"
  action: "gestionuser"

/ajout-utilisateur:
  controller: "User"
  action: "add"


/recupcode:
  controller: "User"
  action: "recupcode"

/changemdp:
  controller: "User"
  action: "changemdp"

/supprimer-utilisateur:
  controller: "User"
  action: "remove"

/utilisateur:
  controller: "User"
  action: "default"

/inscription:
  controller: "User"
  action: "register"

/mdpoublie:
  controller: "User"
  action: "forget"