/:
  controller: "User"
  action: "login"

/deconnexion:
  controller: "User"
  action: "deconnecter"

/dashboard: 
  controller: "Dashboard"
  action: "dashboard"

/mailbox:
  controller: "Mail"
  action: "mail"

/apparence:
  controller: "Apparence"
  action: "apparence"

/forum: 
  controller: "Forum"
  action: "forum"

/ajout-article:
  controller: "Forum"
  action: "addarticle"

/article:
  controller: "Forum"
  action: "updatearticleview"

/modificaton-article:
  controller: "Forum"
  action: "updatearticle"

/resolution-article:
  controller: "Forum"
  action: "resolvearticle"

/suppression-article:
  controller: "Forum"
  action: "removearticle"

/lire-article:
  controller: "Forum"
  action: "readarticle"

/ajout-message:
  controller: "Forum"
  action: "addmessagearticle"

/message:
  controller: "Forum"
  action: "updatemessagearticleview"

/modification-message:
  controller: "Forum"
  action: "updatemessagearticle"

/suppression-message:
  controller: "Forum"
  action: "removemessagearticle"

/bannir-utilisateur:
  controller: "Forum"
  action: "banuser"

/ajout-categorie:
  controller: "Forum"
  action: "addcategory"

/categorie:
  controller: "Forum"
  action: "updatecategoryview"

/modification-categorie:
  controller: "Forum"
  action: "updatecategory"

/suppression-categorie:
  controller: "Forum"
  action: "removecategory"

/media: 
  controller: "Media"
  action: "media"

/page: 
  controller: "Page"
  action: "page"

/lien: 
  controller: "Page"
  action: "lien"

/parametre:
  controller: "Parametre"
  action: "parametre"

/gestionuser:
  controller: "User"
  action: "gestionuser"

/ajout-utilisateur:
  controller: "User"
  action: "add"


/recupcode:
  controller: "User"
  action: "recupcode"

/changemdp:
  controller: "User"
  action: "changemdp"

/supprimer-utilisateur:
  controller: "User"
  action: "remove"

/utilisateur:
  controller: "User"
  action: "default"

/inscription:
  controller: "User"
  action: "register"

/mdpoublie:
  controller: "User"
  action: "forget"