/:
  controller: "user"
  action: "login"

/deconnexion:
  controller: "user"
  action: "deconnecter"

/dashboard: 
  controller: "dashboard"
  action: "dashboard"

/mailbox:
  controller: "mail"
  action: "mail"

/apparence:
  controller: "apparence"
  action: "apparence"

/forum: 
  controller: "forum"
  action: "forum"

/media: 
  controller: "media"
  action: "media"

/page: 
  controller: "page"
  action: "page"

/parametre:
  controller: "parametre"
  action: "parametre"

/gestionuser:
  controller: "user"
  action: "gestionuser"


/ajout-utilisateur:
  controller: "user"
  action: "add"

/supprimer-utilisateur:
  controller: "user"
  action: "remove"

/utilisateur:
  controller: "user"
  action: "default"

/inscription:
  controller: "user"
  action: "register"

/mdpoublie:
  controller: "user"
  action: "forget"